services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=tKgSGz-6P3VhGQrbPoEf
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - elastic

  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'datamine'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./db:/var/lib/mysql

networks:
  elastic:
    name: elastic
    driver: bridge
